# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs


name: 🚀 Deploy app on push

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12.1]
     

    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v2
         
      - name: 🔨 Detect package manager
        id: detect-package-manager
        run: 
         npm install
      - name: Build Creating
        run: npm run build
        
      - name: List output files
        run: ls
         
      - name: 🚚 Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: ${{ steps.detect-package-manager.outputs.manager }}
 
      - name: 📂 deploy file to server
      
        #uses: verbindingsfout/sftp-mirror@v1.6
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        #uses: cypress-io/github-action@v2
        
        with:
            username: ${{ secrets.FTP_USERNAME }}
            server: ${{ secrets.FTP_SERVER }}
            ssh_private_key: ${{ secrets.SSH_PUBLIC_KEY }}
            local_path: './build/*'
            remote_path: '/var/www/html/advisionary'
            sftpArgs: '-o ConnectTimeout=5'

  
